version: "3.7"
services:
  api:
    build: .
    restart: unless-stopped

    command: ["node", "dist/server.js"]

    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=info
      - CLIENT_ID=your_app_client_id
      - APP_ACCESS_TOKEN=your_app_access_token
      - EVENTSUB_SECRET=random_string_secret_to_validate_eventsub_signatures

  bot:
    build: .
    restart: unless-stopped

    command: ["./wait-for-it.sh", "server:8080", "--timeout=60", "--", "node", "dist/bot.js" ]

    environment:
      - LOG_LEVEL=info
      - SOCKETIO_SERVER_ADDR=http://api:8080
      - CHATBOT_OAUTH_TOKEN=your_bot_oauth_token
      - CHATBOT_CHANNELS=space_separated_list_of_channel_the_bot_should_join

    depends_on:
      - api
